nelmio_api_doc:
    documentation:
        info:
            title: Test API
            description: This is a Symfony Test API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api
